<template>
  <div>
    <div class="page-title">
      <h3>{{ $route.name }}</h3>
    </div>
    <!-- РКДВ, РШ, ВКЛ, ВЛЛ -->
    <div>
      <div class="row" v-for="(block, index) in req" :key="index">
        <div class="col s12 m4" v-for="request in block" :key="request.number">
          <card-request :request="request" />
        </div>
      </div>
    </div>

    <div class="fixed-action-btn">
      <router-link to="/request">
        <a class="btn-floating btn-large waves-effect waves-light blue darken-3">
          <i class="large material-icons">add</i>
        </a>
      </router-link>
    </div>
  </div>
</template>

<script>
import CardRequest from '../components/CardRequest.vue'
import utils from '@/utils/card.utils'

export default {
  components: { CardRequest },
  computed: {
    req() {
      return utils.arrayCardTransform(this.requests, 3)
    },
  },
  data: () => ({
    requests: [
      {
        cargo: 'Легковые автомобили',
        date: '26.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda N WGN (JH2-1207367)',
            container: '',
            document: '744521КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8732/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '26.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Isis (ZGM15-0010616)',
            container: '',
            document: '744496КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1520,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Lexus LX470 (В277ММ 41, JTJHT00W143539551)',
            container: '',
            document: '744497КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2450,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8713/21',
        out: 'г. Владивосток',
        status: 'Груз принят ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '25.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Wish (ZGE25-0007879)',
            container: '',
            document: '744396КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda CR-V (В292НУ 41, SHSRE78709U003019)',
            container: '',
            document: '744397КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1600,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Corolla (Е343РР 27, AE1105094434)',
            container: '',
            document: '744398КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1060,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8631/21',
        out: 'г. Владивосток',
        status: 'Груз принят ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '25.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Fit Hybrid (GP6-1202734)',
            container: '',
            document: '744316КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Ridgeline (Н669АЕ 125, 2HJYK16487H512426)',
            container: '',
            document: '744317КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 2043,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8596/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '24.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Cresta (Н432ТН 125, JZX1056000547)',
            container: '',
            document: '744146КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8504/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '24.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Subaru Forester (SH5008909)', container: '', document: '744118КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1450 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (KZJ95-0025063)',
            container: '',
            document: '744119КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 2000,
          },
          { cargo: 'Легковые автомобили', cargoadd: 'Subaru Legacy B4 (BL5085030)', container: '', document: '744120КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1360 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8482/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '24.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Ignis Hybrid (FF21S-131363)',
            container: '',
            document: '744116КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8480/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '11.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Subaru Forester (SJ5-072255)', container: '', document: '741730КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1500 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8466/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '12.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Corolla (Е343РР 27, AE1105094434)',
            container: '',
            document: '741942КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1060,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Трякин Д. В.',
        number: '8463/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '12.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Hice (Р998ОХ 125, LH850005498)',
            container: '',
            document: '741943КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1740,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7577/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Трякин Д. В.',
        number: '8462/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '12.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Expert (Х334ЕТ, VNW11502135)',
            container: '',
            document: '741944КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1470,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Трякин Д. В.',
        number: '8461/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru Legacy (Т494РО 25, BE5050192)',
            container: '',
            document: '741077КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1480,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7578/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Трякин Д. В.',
        number: '8460/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '18.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Tundra (В121АТ 41, 5TFDW5F16AX107415)',
            container: '',
            document: '743127КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2505,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8459/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '11.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Grace (GM5-1000213)',
            container: '',
            document: '741720КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Voxy (ZRR75-0101337)',
            container: '',
            document: '741721КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1660,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8458/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '13.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (JTEBU29J905010402)',
            container: '',
            document: '742412КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1900,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru XV Hybrid (GPE-017772)',
            container: '',
            document: '742413КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7579/КМП', payment: '', status: 'Счет не оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '8457/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '19.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Suzuki Swift (ZD83S-102320)', container: '', document: '743369КМП', flight: 21055, ship: 'В. ХЛОПИН', size: 0, status: 'На судне', weight: 1100 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Isuzu Bighorn (Т740ВХ 125, UBS26GW7201366)',
            container: '',
            document: '743370КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7581/КМП', payment: '', status: 'Счет не оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '8454/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '20.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (GDJ150-0023488)',
            container: '',
            document: '743510КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 2000,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Isuzu Bighorn (UBS26GW-7202296)',
            container: '',
            document: '743511КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8453/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '20.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota FJ Cruiser (GSJ15-0137553)',
            container: '',
            document: '743512КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 2000,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7582/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8452/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '21.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Nissan Leaf (AZE0-108814)', container: '', document: '743601КМП', flight: 21055, ship: 'В. ХЛОПИН', size: 0, status: 'На судне', weight: 1400 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7583/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8451/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '21.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Toyota Ist (NCP115-2000315)', container: '', document: '743790КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1100 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8390/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '21.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Shuttle Hybrid (GP8-1005474)',
            container: '',
            document: '743751КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1300,
          },
          { cargo: 'Легковые автомобили', cargoadd: 'Toyota Vitz (NSP135-2019960)', container: '', document: '743752КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1080 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Lexus GX460 (JTJBM7FX1A5017207)',
            container: '',
            document: '743753КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2406,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser (В159НУ 41, JTMHT05J304046247)',
            container: '',
            document: '743754КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2690,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8372/21',
        out: 'г. Владивосток',
        status: 'Груз принят ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '21.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Honda Fit (GK4-1205456)', container: '', document: '743597КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1200 },
          { cargo: 'Легковые автомобили', cargoadd: 'Honda Freed (GB4-1606277)', container: '', document: '743598КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1300 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Aristo (В006ВК 125, JZS1600138611)',
            container: '',
            document: '743599КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1600,
          },
          { cargo: 'Легковые автомобили', cargoadd: 'Nissan Terrano (RR50-015326)', container: '', document: '743600КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1300 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8341/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '06.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru XV Hybrid (GPE-031010)',
            container: '',
            document: '741239КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8331/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '20.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Infiniti FX35 (JNRAS08W53X207602)',
            container: '',
            document: '743532КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1700,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Fortuner (MR0KX3ESX00811417)',
            container: '',
            document: '743533КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1900,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Alphard (В276НУ 41, AYH300017767)',
            container: '',
            document: '743534КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 2170,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8294/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '20.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Tacoma (В265НУ 41, 3TMDZ5BN2HM026220)',
            container: '',
            document: '743508КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 2190,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Qashqai (Е078ХТ 777, SJNFBNJ10U2143415)',
            container: '',
            document: '743509КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1540,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7571/КМП', payment: '', status: 'Счет не оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '8274/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '19.05.2021',
        documents: [
          {
            cargo: 'Автомоб. груз не поимен в алф',
            cargoadd: 'Nissan Atlas (В227НУ 41, BF22066907)',
            container: '',
            document: '743367КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 2830,
          },
          {
            cargo: 'Автомоб. груз не поимен в алф',
            cargoadd: 'Nissan Atlas (В230НТ 41, AGF22151419)',
            container: '',
            document: '743368КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1890,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8146/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (JTEBX9FJ9BK052450)',
            container: '',
            document: '741075КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 2050,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7204/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Трякин Д. В.',
        number: '8130/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown (AWS211-6012326)',
            container: '',
            document: '741076КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Трякин Д. В.',
        number: '8129/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '11.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown Hybrid (AWS211-6012326)',
            container: '',
            document: '741690КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7189/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8124/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '11.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Daimler Chrysler (Е736СК 124, 1J4GW88S6XY500622)',
            container: '',
            document: '741696КМП',
            flight: 21062,
            ship: 'О. ТАВОЛЖАНСКИЙ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1881,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '21.05.2021', number: '7440/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8123/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '04.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda CR-V (RD1-1212581)',
            container: '',
            document: '740812КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1380,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8122/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Fit Shuttle (GG8-3101064)',
            container: '',
            document: '740998КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7188/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8120/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '29.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Shuttle (GP8-1005526)',
            container: '',
            document: '740281КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1400,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Vezel Hybrid (RU4-1206235)',
            container: '',
            document: '740282КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7187/КМП', payment: 21000, status: 'Оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '8119/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '09.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Jimny (JSAFJB43V00564483)',
            container: '',
            document: '737580КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1180,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8118/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '28.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Mitsubishi Pajero Mini (H58A-0902136)',
            container: '',
            document: '740078КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7185/КМП', payment: 10500, status: 'Оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8116/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '18.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Safari (В234НТ 41, WRGY60610305)',
            container: '',
            document: '743126КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 2460,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7572/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '8063/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '18.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Lite Ace Noah (SR50G-0044890)',
            container: '',
            document: '743044КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '8011/21',
        out: 'г. Владивосток',
        status: 'Груз принят в порт',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '13.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (К719ОА 28, KZJ950140554)',
            container: '',
            document: '742411КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Груз принят в порт',
            weight: 1980,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '7651/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '12.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru Forester (SH5-063988)',
            container: '',
            document: '741964КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1520,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota C-HR (NGX50-2015595)',
            container: '',
            document: '741965КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '7559/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '12.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Nissan Leaf (AZE0-054257)', container: '', document: '741941КМП', flight: 21055, ship: 'В. ХЛОПИН', size: 0, status: 'На судне', weight: 1440 },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7576/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Трякин Д. В.',
        number: '7543/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '28.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Rush (J210E-2011230)',
            container: '',
            document: '740080КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7186/КМП', payment: 10500, status: 'Оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '7521/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '28.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'УАЗ 220695 (ХТТ220695М1204983)',
            container: '',
            document: '740086КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2200,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'УАЗ 220695 (ХТТ220695М1204917)',
            container: '',
            document: '740087КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2200,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'УАЗ 220695 (ХТТ220695М1204985)',
            container: '',
            document: '740088КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '7517/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '11.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Corolla Fielder (NZE164-705818171)',
            container: '',
            document: '741729КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7575/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '7471/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '11.05.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Toyota Passo (M710A-0016098)', container: '', document: '741715КМП', flight: 21055, ship: 'В. ХЛОПИН', size: 0, status: 'На судне', weight: 1100 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (RZJ90-0005941)',
            container: '',
            document: '741716КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 2000,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Grand Vitara (JSAJTDA4V00321972)',
            container: '',
            document: '741717КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1659,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Lite Ace Noah (SR500090657)',
            container: '',
            document: '741718КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1570,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Lite Ace Noah (SR500034857)',
            container: '',
            document: '741719КМП',
            flight: 21055,
            ship: 'В. ХЛОПИН',
            size: 0,
            status: 'На судне',
            weight: 1570,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '24.05.2021', number: '7574/КМП', payment: '', status: 'Счет не оплачен', summa: 52500 },
        manager: 'Кирильчук С. С.',
        number: '7465/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '04.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Daihatsu Terios Kid (J111G-502314)',
            container: '',
            document: '740811КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7182/КМП', payment: 10500, status: 'Оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '7449/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '11.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Fit (GK4-1203292)',
            container: '',
            document: '741650КМП',
            flight: 21062,
            ship: 'О. ТАВОЛЖАНСКИЙ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1200,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Teana (Н438КС 125, J31008954)',
            container: '',
            document: '741651КМП',
            flight: 21062,
            ship: 'О. ТАВОЛЖАНСКИЙ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1450,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '21.05.2021', number: '7443/КМП', payment: '', status: 'Счет не оплачен', summa: 21000 },
        manager: 'Трякин Д. В.',
        number: '7418/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '06.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Mazda Familia (VZNY12-516006)',
            container: '',
            document: '741238КМП',
            flight: 21062,
            ship: 'О. ТАВОЛЖАНСКИЙ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '21.05.2021', number: '7446/КМП', payment: '', status: 'Счет не оплачен', summa: 10500 },
        manager: 'Кирильчук С. С.',
        number: '7255/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '19.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Mazda Bongo (У050ЕУ25)',
            container: '',
            document: '738633КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '7169/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '19.04.2021',
        documents: [{ cargo: 'Легковые автомобили', cargoadd: '', container: '', document: '738635КМП', flight: '', ship: '', size: 0, status: 'Регистрация груза для отправки', weight: 0 }],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '7167/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '20.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda N-box (JF2-1514386)',
            container: '',
            document: '738709КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1000,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '7166/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '20.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota CH-R (NGX50-2014954)',
            container: '',
            document: '738711КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '7164/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '22.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Rush (J210E-2089510)',
            container: '',
            document: '739396КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '7157/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '26.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Fit (GK4-1204719)',
            container: '',
            document: '739626КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '7152/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '31.03.2021',
        documents: [
          { cargo: 'Легковые автомобили', cargoadd: 'Honda Shuttle (GP8-1005214)', container: '', document: '735897КМП', flight: '', ship: '', size: 0, status: 'Груз принят в порт', weight: 1300 },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Ractis (NCP125-2010016)',
            container: '',
            document: '735899КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota C-HR (NGX50-2014962)',
            container: '',
            document: '735900КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota C-HR (NGX50-2014714)',
            container: '',
            document: '735901КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '7151/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '05.05.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Rush (J210E-2004874)',
            container: '',
            document: '740995КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1300,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown (GRS201-0001434)',
            container: '',
            document: '740996КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7179/КМП', payment: 21000, status: 'Оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '7103/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '15.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'TOYOTA LAND CRUISER 200 (В460ММ41)',
            container: '',
            document: '738162КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2750,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'TOYOTA LAND CRUISER PRADO (В511ММ41)',
            container: '',
            document: '738163КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '6864/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '19.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Qashqai (SJNFBNJ10U2131521)',
            container: '',
            document: '738345КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '6861/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '09.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Lexus LX570 (JTJHY00WX04103920)',
            container: '',
            document: '737573КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 2665,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Lexus RX350 (JTJBK11A902442180)',
            container: '',
            document: '737574КМП',
            flight: 21056,
            ship: 'И. КАПРАЛОВ',
            size: 0,
            status: 'Выгружен с судна',
            weight: 1900,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: '', date: '19.05.2021', number: '7177/КМП', payment: 21000, status: 'Оплачен', summa: 21000 },
        manager: 'Кирильчук С. С.',
        number: '6768/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '28.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Vanette (SKP2MN-204257)',
            container: '',
            document: '740070КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '6658/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '06.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Tundra (К070ОМ 154, 5TBBV54118S505749)',
            container: '',
            document: '736916КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '6419/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '22.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Z350 (В127НХ41)',
            container: '',
            document: '739391КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1450,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '6225/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '16.04.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'TOYOTA FIELDER (О174КР125)',
            container: '',
            document: '738219КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1200,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'HONDA FIT (GP6-1301294)',
            container: '',
            document: '738220КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'HONDA FIT (GP6-1202924)',
            container: '',
            document: '738221КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'SUZUKI JIMNY (JB23W-529991)',
            container: '',
            document: '738222КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1000,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Чепижко Р. С.',
        number: '5680/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '30.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown (М021ТУ 65, GRS2010001434)',
            container: '',
            document: '735535КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1690,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '4807/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '15.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Carina (ST2156003095)',
            container: '',
            document: '733541КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1150,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '4703/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '23.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Escudo (TSMLYE21S-00273755)',
            container: '',
            document: '734938КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1600,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3900/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru Legacy B4 (BE5050192)',
            container: '',
            document: '732649КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1480,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3759/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '17.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Mazda Bongo (SE28M-401985)',
            container: '',
            document: '734095КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3519/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '16.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (RZJ90-0001435)',
            container: '',
            document: '733665КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1720,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3369/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '25.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Renault Duster (К953ВО 797, X7LHSRHGD66169415)',
            container: '',
            document: '731741КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1466,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3360/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '10.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Lexus LX570 (JTJHY00W504004955)',
            container: '',
            document: '733125КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2660,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '3057/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '24.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Safari (WRGY61-800414)',
            container: '',
            document: '731330КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1800,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '2980/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '09.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Escudo (В723НХ 41, TD02W102476)',
            container: '',
            document: '732831КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1260,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '2919/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '05.03.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (А861ХР 41, GRJ1210004292)',
            container: '',
            document: '732684КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2000,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '2792/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '16.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Swift (ZD72S-313159)',
            container: '',
            document: '730688КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '2470/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '17.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown Hybrid (AWS211-6007158)',
            container: '',
            document: '730855КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1888/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '16.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Corolla Axio (NZE164-7044076)',
            container: '',
            document: '730716КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1200,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Suzuki Solio (MA26S-153008)',
            container: '',
            document: '730717КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1000,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan Note (NE12-205080)',
            container: '',
            document: '730718КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1781/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '18.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru Impreza (Н229ОР 125, GG2033669)',
            container: '',
            document: '727948КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1477/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '19.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan X-Trail (NT32-042917)',
            container: '',
            document: '728014КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1474/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '19.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan X-Trail (NT32-042644)',
            container: '',
            document: '728018КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan X-Trail (NT32-041912)',
            container: '',
            document: '728019КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Rush (J210E-0034237)',
            container: '',
            document: '728020КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1470/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '22.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Subaru B4 (BL5-088135)',
            container: '',
            document: '728445КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '1467/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Автотехника',
        date: '13.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Land Cruiser Prado (TRJ150-0079147)',
            container: '',
            document: '727569КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1900,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Vezel Hybrid (RU4-1015377)',
            container: '',
            document: '727570КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Rush (J210E-2000798)',
            container: '',
            document: '727571КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Vitz (NSP135-2058536)',
            container: '',
            document: '727572КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1100,
          },
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan X-Trail (NT32-042120)',
            container: '',
            document: '727573КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '967/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '14.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Crown (UZS1730003185)',
            container: '',
            document: '727671КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1935,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '963/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '01.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Mitsubishi Delica (В141МО 41, PD6W0500772)',
            container: '',
            document: '729080КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 2400,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '941/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '01.02.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Nissan X-Trail (JN1TBNT30U0125583)',
            container: '',
            document: '729059КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1500,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '927/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '19.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Honda Grace Hybrid (GM5-110373)',
            container: '',
            document: '728012КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1300,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '496/21',
        out: 'г. Владивосток',
        status: 'Груз отгружен ЧАСТИЧНО',
        type: 'Каботаж',
      },
      {
        cargo: 'Легковые автомобили',
        date: '15.01.2021',
        documents: [
          {
            cargo: 'Легковые автомобили',
            cargoadd: 'Toyota Probox (NCP165-0041739)',
            container: '',
            document: '727715КМП',
            flight: '',
            ship: '',
            size: 0,
            status: 'Регистрация груза для отправки',
            weight: 1200,
          },
        ],
        in: 'г. П-Камчатский',
        invoice: { additional: 0, date: '', number: '/КМП', payment: '', status: 'Счет не оплачен', summa: 0 },
        manager: 'Кирильчук С. С.',
        number: '404/21',
        out: 'г. Владивосток',
        status: 'Новая',
        type: 'Каботаж',
      },
    ],
  }),
}
</script>

<style></style>
